sudo: required
services:
  - docker

before_install:
  - docker build -t danynarcisse/learning-docker-react -f Dockerfile.dev .

script:
  - docker run danynarcisse/learning-docker-react npm run ci_test -- --coverage